import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShieldCheck } from "lucide-react";
import { Navigate } from "react-router-dom";
import { useAuth } from "../lib/auth";
export function LoginPage() {
    const auth = useAuth();
    if (auth.token) {
        return _jsx(Navigate, { replace: true, to: "/" });
    }
    return (_jsx("div", { className: "flex min-h-screen items-center justify-center p-6", children: _jsxs("div", { className: "grid max-w-5xl gap-6 lg:grid-cols-[1.1fr_0.9fr]", children: [_jsxs("section", { className: "rounded-[2rem] bg-brand-ink p-10 text-white shadow-panel", children: [_jsxs("div", { className: "inline-flex items-center gap-3 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm", children: [_jsx(ShieldCheck, { size: 18 }), "Kalite ve egitim raporlama merkezi"] }), _jsxs("h1", { className: "mt-8 text-5xl font-semibold leading-tight", children: ["CEO sunumu icin hazir,", _jsx("br", {}), "aylik kalite raporlama akisi."] }), _jsx("p", { className: "mt-4 max-w-xl text-lg text-slate-200", children: "Audit, kayip sorular, CSAT ve QT performansi tek ekranda. Draft import, yayinlama ve sunum modu tek akista." })] }), _jsxs("section", { className: "rounded-[2rem] border border-slate-200 bg-white p-8 shadow-panel", children: [_jsx("p", { className: "text-sm font-semibold uppercase tracking-[0.22em] text-brand-coral", children: "Kimlik dogrulama" }), _jsx("h2", { className: "mt-3 text-3xl font-semibold text-slate-950", children: "Giris yap" }), _jsx("p", { className: "mt-2 text-sm text-slate-500", children: "Uretimde yalniz Google girisi kullanilir. Gelistirme modunda bypass butonlari acilabilir." }), _jsx("button", { className: "mt-8 w-full rounded-[10px] bg-brand-ink px-5 py-4 text-base font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-300", disabled: auth.authMode === "none", onClick: () => void auth.loginWithGoogle(), type: "button", children: "Google ile giris yap" }), import.meta.env.VITE_DEV_AUTH_MODE === "true" ? (_jsxs("div", { className: "mt-8 rounded-3xl border border-dashed border-slate-300 p-4", children: [_jsx("p", { className: "text-sm font-semibold text-slate-900", children: "Gelistirme bypass" }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-3", children: [_jsx("button", { className: "rounded-full border px-4 py-2 text-sm font-semibold", onClick: () => auth.loginAsDev("admin"), type: "button", children: "Admin" }), _jsx("button", { className: "rounded-full border px-4 py-2 text-sm font-semibold", onClick: () => auth.loginAsDev("team"), type: "button", children: "Team" }), _jsx("button", { className: "rounded-full border px-4 py-2 text-sm font-semibold", onClick: () => auth.loginAsDev("ceo"), type: "button", children: "CEO" })] })] })) : null] })] }) }));
}
